### ISSUE TITLE
BadParcelableException

### ISSUE THREAD

**Issue by ojasgulati** [openMF/self-service-app#1264]
**Summary:**
sometimes opening mifos application, It throws BadParcelable exception.
Summarize your issue in one sentence (what goes wrong, what did you expect to happen).

**Steps to reproduce:**
How can we reproduce the issue?
This is error doesn't produce every time. Mostly It happens when we leave app in memory ideal for some time.
**Expected behaviour:**
Every time the app should open correctly.
What did you expect the app to do?
The app should work fine every time.
**Observed behaviour:**
The app is crashing.
What did you see instead?  Describe your issue in detail here.

StackTrace:

``` 2020-01-09 09:09:43.660 17418-17418/org.mifos.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mifos.mobile, PID: 17418
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mifos.mobile/org.mifos.mobile.ui.activities.HomeActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android:viewHierarchyState
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android:viewHierarchyState
        at android.os.Parcel.readParcelableCreator(Parcel.java:2839)
        at android.os.Parcel.readParcelable(Parcel.java:2765)
        at org.mifos.mobile.models.client.Client.<init>(Client.java:287)
        at org.mifos.mobile.models.client.Client$1.createFromParcel(Client.java:297)
        at org.mifos.mobile.models.client.Client$1.createFromParcel(Client.java:294)
        at android.os.Parcel.readParcelable(Parcel.java:2774)
        at android.os.Parcel.readValue(Parcel.java:2668)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3037)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.BaseBundle.getBoolean(BaseBundle.java:894)
        at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:7446)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7131)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 


 if (client.getAttendanceType().getValue().equals("Invalid")) {
                            client.getAttendanceType().setValue("1");
                            client.getAttendanceType().setCode("attendanceType.present");
                        }
```

**Device and Android version:**

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?
Model - Asus Zenfone Max Pro M1
Android Version - 9.0 (Stock)

I would like to work on this issue.

**Comment by vibhusharma101** [comment]
@luckyman20  can I work on this issue?
