### ISSUE TITLE
NPE while making Transfer 

### ISSUE THREAD

**Issue by therajanmaurya** [openMF/self-service-app#320]
**Summary:**
```
FATAL EXCEPTION: main
Process: org.mifos.selfserviceapp, PID: 28897
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer org.mifos.selfserviceapp.models.templates.account.AccountType.getId()' on a null object reference
at org.mifos.selfserviceapp.ui.fragments.SavingsMakeTransferFragment.makeTransfer(SavingsMakeTransferFragment.java:196)
at org.mifos.selfserviceapp.ui.fragments.SavingsMakeTransferFragment$2.onClick(SavingsMakeTransferFragment.java:153)
at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by dilpreet2028** [comment]
@therajanmaurya I am not able to replicate this exception, do you remember which account number you chose? but I think this might be due to api is not returning compelete information i.e. about the AccountType for a particular account as it was able to fetch information about accountId and clientId from that object before trying to fetch `getAccountType().getId()`.

**Comment by therajanmaurya** [comment]
4th Account from SavingsAccount. try transfer to account number 37

**Comment by dilpreet2028** [comment]
<img src="https://user-images.githubusercontent.com/12071739/27515040-1614806e-59b8-11e7-8fd8-a37def3cafc1.gif"/>

I am able to transfer to and from account no 37
