### ISSUE TITLE
Crash on adding new Loan Account on Nougat

### ISSUE THREAD

**Issue by tarun0** [openMF/self-service-app#518]
**Summary:**

App crashes when new Loan Account _Floating Action Button_ is clicked.

**Steps to reproduce:**

Click on `Total Loan` in Account Overview on the Home Screen. Click on the _Floating Action Button (+)_

**Expected behavior:**

Show the screen for new loan application.

**Observed behavior:**

App crashed.

**Device and Android version:**

Motorola G5S Plus. Stock Android - Nougat (7.1.1) API 25.

**Screenshots:**

![bug](https://user-images.githubusercontent.com/12914286/34401538-dc2bd8d8-ebc1-11e7-9df2-47d974a48d7e.gif)

**Miscellaneous Info**

*Log*

```
12-28 11:21:33.747 29086-29086/org.mifos.mobilebanking E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: org.mifos.mobilebanking, PID: 29086
                                                                         java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 550872 bytes
                                                                             at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3805)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                                          Caused by: android.os.TransactionTooLargeException: data parcel size 550872 bytes
                                                                             at android.os.BinderProxy.transactNative(Native Method)
                                                                             at android.os.BinderProxy.transact(Binder.java:615)
                                                                             at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3716)
                                                                             at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3797)
```

*Relevant SO thread*

https://stackoverflow.com/questions/39098590/android-os-transactiontoolargeexception-on-nougat#39747117

**Comment by dilpreet2028** [comment]
@tarun0 , this issue is caused due to #413 i.e. storing of bitmaps in bundle and that will be fixed soon
