### ISSUE TITLE
App crashing while making payment in Loans Section

### ISSUE THREAD

**Issue by sridharjajoo** [openMF/self-service-app#726]
**Steps to reproduce:**
1) Go to Accounts -> Loan
2) Select the loan which is Active
3) Select Make Payment
4) Fill the form and select Transfer.

**Expected behaviour:**
The app shouldn't crash.

**Device and Android version:**
Xiaomi Redmi Note 3 (6.0.1)

**Screenshots:**
![device-2018-03-13-164810](https://user-images.githubusercontent.com/20684618/37338954-026ca4ac-26df-11e8-8c28-d1a818f03306.gif)

**Comment by sridharjajoo** [comment]
@dilpreet96 @therajanmaurya @droidchef @satyan I would like to work on this issue.

**Comment by therajanmaurya** [comment]
@miPlodder this issue still exist 
```
Process: org.mifos.mobilebanking, PID: 6753
io.reactivex.exceptions.UndeliverableException: java.lang.ClassCastException: org.mifos.mobilebanking.ui.activities.LoanAccountContainerActivity cannot be cast to org.mifos.mobilebanking.ui.activities.SavingsAccountContainerActivity
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.ClassCastException: org.mifos.mobilebanking.ui.activities.LoanAccountContainerActivity cannot be cast to org.mifos.mobilebanking.ui.activities.SavingsAccountContainerActivity
at org.mifos.mobilebanking.ui.fragments.TransferProcessFragment.showTransferredSuccessfully(TransferProcessFragment.java:164)
at org.mifos.mobilebanking.presenters.TransferProcessPresenter$1.onNext(TransferProcessPresenter.java:85)
at org.mifos.mobilebanking.presenters.TransferProcessPresenter$1.onNext(TransferProcessPresenter.java:70)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
at android.os.Handler.handleCallback(Handler.java:746) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5443) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by miPlodder** [comment]
@therajanmaurya It's duplicate issue. Please check #813

**Comment by therajanmaurya** [comment]
duplicate issue #813
