### ISSUE TITLE
Self Service App / Mifos Mobile Crashes on Samsung with  Android version 4.4.2

### ISSUE THREAD

**Issue by RajaVamsi11** [openMF/self-service-app#886]
**Summary:**
@therajanmaurya @dilpreet96 
When I tried to run the app from the android studio building apk from the latest source code development branch builds well and installs on Samsung but launching it crashes.
with a message "Unfortunately Mifos Mobile has stopped"
I tried disabling instant run but it does not work.

**Log Cat Errors:**
10-01 16:55:56.275 26645-26645/? E/dalvikvm: >>>>> Normal User
    >>>>> org.mifos.mobilebanking [ userId:0 | appId:10214 ]
10-01 16:55:56.355 26645-26645/org.mifos.mobilebanking E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mifos.mobilebanking, PID: 26645
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.mifos.mobilebanking-4.apk"],nativeLibraryDirectories=[/data/app-lib/org.mifos.mobilebanking-4, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5218)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4810)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4693)
        at android.app.ActivityThread.access$1600(ActivityThread.java:173)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5579)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/data/app/org.mifos.mobilebanking-4.apk"],nativeLibraryDirectories=[/data/app-lib/org.mifos.mobilebanking-4, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5203)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4810) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4693) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:173) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5579) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
        at dalvik.system.NativeStart.main(Native Method) 

**Device and Android version:**

Model device: Samsung Galaxy S5 What Android
Model version: 4.4.2

**Comment by prashantkh19** [comment]
@RajaVamsi11 Can I work on it?

**Comment by RajaVamsi11** [comment]
@prashantkh19 Sure.
